version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: syncpay-postgres
    environment:
      POSTGRES_USER: syncpay_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: syncpay_db
    ports:
      - "5432:5432"
    volumes:
      - syncpay-pgdata:/var/lib/postgresql/data

volumes:
  syncpay-pgdata: